import { Hero } from '../models/hero.model';

export const MOCK_HEROES: Hero[] = [
  {
    id: 70,
    name: 'Batman',
    description: 'Bruce Wayne',
    image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/70-batman.jpg',
    publisher: 'DC Comics',
    alignment: 'good',
    firstAppearance: 'Detective Comics #27',
    powerstats: { intelligence: 100, strength: 26, speed: 27, durability: 50, power: 47, combat: 100 },
  },
  {
    id: 69,
    name: 'Batman Beyond',
    description: 'Terry McGinnis',
    image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/69-batman-beyond.jpg',
    publisher: 'DC Comics',
    alignment: 'good',
    firstAppearance: 'Batman Beyond #1',
    powerstats: { intelligence: 81, strength: 40, speed: 29, durability: 55, power: 63, combat: 90 },
  },
  {
    id: 71,
    name: 'Batman II',
    description: 'Dick Grayson',
    image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/71-batman-ii.jpg',
    publisher: 'DC Comics',
    alignment: 'good',
    firstAppearance: '-',
    powerstats: { intelligence: 88, strength: 11, speed: 33, durability: 28, power: 36, combat: 100 },
  },
  {
    id: 1,
    name: 'Superman',
    description: 'Kal-El',
    image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/1-superman.jpg',
    publisher: 'DC Comics',
    alignment: 'good',
    firstAppearance: 'Action Comics #1',
    powerstats: { intelligence: 94, strength: 100, speed: 100, durability: 100, power: 100, combat: 85 },
  },
  {
    id: 2,
    name: 'Spider-Man',
    description: 'Peter Parker',
    image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/2-spider-man.jpg',
    publisher: 'Marvel Comics',
    alignment: 'good',
    firstAppearance: 'Amazing Fantasy #15',
    powerstats: { intelligence: 90, strength: 78, speed: 63, durability: 75, power: 74, combat: 85 },
  },
  {
    id: 3,
    name: 'Wonder Woman',
    description: 'Diana Prince',
    image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/3-wonder-woman.jpg',
    publisher: 'DC Comics',
    alignment: 'good',
    firstAppearance: 'All Star Comics #8',
    powerstats: { intelligence: 88, strength: 100, speed: 79, durability: 100, power: 100, combat: 100 },
  },
  {
    id: 4,
    name: 'Iron Man',
    description: 'Tony Stark',
    image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/4-iron-man.jpg',
    publisher: 'Marvel Comics',
    alignment: 'good',
    firstAppearance: 'Tales of Suspense #39',
    powerstats: { intelligence: 100, strength: 85, speed: 58, durability: 85, power: 100, combat: 64 },
  },
  {
    id: 5,
    name: 'Joker',
    description: 'Jack Napier',
    image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/5-joker.jpg',
    publisher: 'DC Comics',
    alignment: 'bad',
    firstAppearance: 'Batman #1',
    powerstats: { intelligence: 100, strength: 11, speed: 18, durability: 58, power: 35, combat: 70 },
  },
  {
    id: 6,
    name: 'Captain America',
    description: 'Steve Rogers',
    image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/6-captain-america.jpg',
    publisher: 'Marvel Comics',
    alignment: 'good',
    firstAppearance: 'Captain America Comics #1',
    powerstats: { intelligence: 69, strength: 19, speed: 38, durability: 55, power: 60, combat: 100 },
  },
  {
    id: 7,
    name: 'Thor',
    description: 'Thor Odinson',
    image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/7-thor.jpg',
    publisher: 'Marvel Comics',
    alignment: 'good',
    firstAppearance: 'Journey into Mystery #83',
    powerstats: { intelligence: 69, strength: 100, speed: 83, durability: 100, power: 100, combat: 100 },
  },
  {
    id: 8,
    name: 'Hulk',
    description: 'Bruce Banner',
    image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/8-hulk.jpg',
    publisher: 'Marvel Comics',
    alignment: 'good',
    firstAppearance: 'Incredible Hulk #1',
    powerstats: { intelligence: 88, strength: 100, speed: 47, durability: 100, power: 81, combat: 85 },
  },
  {
    id: 9,
    name: 'Aquaman',
    description: 'Arthur Curry',
    image: 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/9-aquaman.jpg',
    publisher: 'DC Comics',
    alignment: 'good',
    firstAppearance: 'More Fun Comics #73',
    powerstats: { intelligence: 81, strength: 85, speed: 79, durability: 80, power: 83, combat: 80 },
  },
];

export const MOCK_SINGLE_HERO = MOCK_HEROES[0]; // Batman

export function createMockHero(overrides: Partial<Hero> = {}): Hero {
  return {
    id: 999,
    name: 'Test Hero',
    description: 'A test hero description for testing purposes',
    image: 'https://example.com/hero.jpg',
    publisher: 'Test Comics',
    alignment: 'good',
    firstAppearance: 'Test #1',
    ...overrides,
  };
}
