import { Hero } from '../models/hero.model';

const BASE = 'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images';

export const MOCK_HEROES: Hero[] = [
  {
    id: 70,
    name: 'Batman',
    description: 'Bruce Wayne',
    image: `${BASE}/md/70-batman.jpg`,
    images: {
      xs: `${BASE}/xs/70-batman.jpg`,
      sm: `${BASE}/sm/70-batman.jpg`,
      md: `${BASE}/md/70-batman.jpg`,
      lg: `${BASE}/lg/70-batman.jpg`,
    },
    publisher: 'DC Comics',
    alignment: 'good',
    firstAppearance: 'Detective Comics #27',
    powerstats: { intelligence: 100, strength: 26, speed: 27, durability: 50, power: 47, combat: 100 },
  },
  {
    id: 69,
    name: 'Batman Beyond',
    description: 'Terry McGinnis',
    image: `${BASE}/md/69-batman-beyond.jpg`,
    images: {
      xs: `${BASE}/xs/69-batman-beyond.jpg`,
      sm: `${BASE}/sm/69-batman-beyond.jpg`,
      md: `${BASE}/md/69-batman-beyond.jpg`,
      lg: `${BASE}/lg/69-batman-beyond.jpg`,
    },
    publisher: 'DC Comics',
    alignment: 'good',
    firstAppearance: 'Batman Beyond #1',
    powerstats: { intelligence: 81, strength: 40, speed: 29, durability: 55, power: 63, combat: 90 },
  },
  {
    id: 71,
    name: 'Batman II',
    description: 'Dick Grayson',
    image: `${BASE}/md/71-batman-ii.jpg`,
    images: {
      xs: `${BASE}/xs/71-batman-ii.jpg`,
      sm: `${BASE}/sm/71-batman-ii.jpg`,
      md: `${BASE}/md/71-batman-ii.jpg`,
      lg: `${BASE}/lg/71-batman-ii.jpg`,
    },
    publisher: 'DC Comics',
    alignment: 'good',
    firstAppearance: '-',
    powerstats: { intelligence: 88, strength: 11, speed: 33, durability: 28, power: 36, combat: 100 },
  },
  {
    id: 1,
    name: 'Superman',
    description: 'Kal-El',
    image: `${BASE}/md/1-superman.jpg`,
    images: {
      xs: `${BASE}/xs/1-superman.jpg`,
      sm: `${BASE}/sm/1-superman.jpg`,
      md: `${BASE}/md/1-superman.jpg`,
      lg: `${BASE}/lg/1-superman.jpg`,
    },
    publisher: 'DC Comics',
    alignment: 'good',
    firstAppearance: 'Action Comics #1',
    powerstats: { intelligence: 94, strength: 100, speed: 100, durability: 100, power: 100, combat: 85 },
  },
  {
    id: 2,
    name: 'Spider-Man',
    description: 'Peter Parker',
    image: `${BASE}/md/2-spider-man.jpg`,
    images: {
      xs: `${BASE}/xs/2-spider-man.jpg`,
      sm: `${BASE}/sm/2-spider-man.jpg`,
      md: `${BASE}/md/2-spider-man.jpg`,
      lg: `${BASE}/lg/2-spider-man.jpg`,
    },
    publisher: 'Marvel Comics',
    alignment: 'good',
    firstAppearance: 'Amazing Fantasy #15',
    powerstats: { intelligence: 90, strength: 78, speed: 63, durability: 75, power: 74, combat: 85 },
  },
  {
    id: 3,
    name: 'Wonder Woman',
    description: 'Diana Prince',
    image: `${BASE}/md/3-wonder-woman.jpg`,
    images: {
      xs: `${BASE}/xs/3-wonder-woman.jpg`,
      sm: `${BASE}/sm/3-wonder-woman.jpg`,
      md: `${BASE}/md/3-wonder-woman.jpg`,
      lg: `${BASE}/lg/3-wonder-woman.jpg`,
    },
    publisher: 'DC Comics',
    alignment: 'good',
    firstAppearance: 'All Star Comics #8',
    powerstats: { intelligence: 88, strength: 100, speed: 79, durability: 100, power: 100, combat: 100 },
  },
  {
    id: 4,
    name: 'Iron Man',
    description: 'Tony Stark',
    image: `${BASE}/md/4-iron-man.jpg`,
    images: {
      xs: `${BASE}/xs/4-iron-man.jpg`,
      sm: `${BASE}/sm/4-iron-man.jpg`,
      md: `${BASE}/md/4-iron-man.jpg`,
      lg: `${BASE}/lg/4-iron-man.jpg`,
    },
    publisher: 'Marvel Comics',
    alignment: 'good',
    firstAppearance: 'Tales of Suspense #39',
    powerstats: { intelligence: 100, strength: 85, speed: 58, durability: 85, power: 100, combat: 64 },
  },
  {
    id: 5,
    name: 'Joker',
    description: 'Jack Napier',
    image: `${BASE}/md/5-joker.jpg`,
    images: {
      xs: `${BASE}/xs/5-joker.jpg`,
      sm: `${BASE}/sm/5-joker.jpg`,
      md: `${BASE}/md/5-joker.jpg`,
      lg: `${BASE}/lg/5-joker.jpg`,
    },
    publisher: 'DC Comics',
    alignment: 'bad',
    firstAppearance: 'Batman #1',
    powerstats: { intelligence: 100, strength: 11, speed: 18, durability: 58, power: 35, combat: 70 },
  },
  {
    id: 6,
    name: 'Captain America',
    description: 'Steve Rogers',
    image: `${BASE}/md/6-captain-america.jpg`,
    images: {
      xs: `${BASE}/xs/6-captain-america.jpg`,
      sm: `${BASE}/sm/6-captain-america.jpg`,
      md: `${BASE}/md/6-captain-america.jpg`,
      lg: `${BASE}/lg/6-captain-america.jpg`,
    },
    publisher: 'Marvel Comics',
    alignment: 'good',
    firstAppearance: 'Captain America Comics #1',
    powerstats: { intelligence: 69, strength: 19, speed: 38, durability: 55, power: 60, combat: 100 },
  },
  {
    id: 7,
    name: 'Thor',
    description: 'Thor Odinson',
    image: `${BASE}/md/7-thor.jpg`,
    images: {
      xs: `${BASE}/xs/7-thor.jpg`,
      sm: `${BASE}/sm/7-thor.jpg`,
      md: `${BASE}/md/7-thor.jpg`,
      lg: `${BASE}/lg/7-thor.jpg`,
    },
    publisher: 'Marvel Comics',
    alignment: 'good',
    firstAppearance: 'Journey into Mystery #83',
    powerstats: { intelligence: 69, strength: 100, speed: 83, durability: 100, power: 100, combat: 100 },
  },
  {
    id: 8,
    name: 'Hulk',
    description: 'Bruce Banner',
    image: `${BASE}/md/8-hulk.jpg`,
    images: {
      xs: `${BASE}/xs/8-hulk.jpg`,
      sm: `${BASE}/sm/8-hulk.jpg`,
      md: `${BASE}/md/8-hulk.jpg`,
      lg: `${BASE}/lg/8-hulk.jpg`,
    },
    publisher: 'Marvel Comics',
    alignment: 'good',
    firstAppearance: 'Incredible Hulk #1',
    powerstats: { intelligence: 88, strength: 100, speed: 47, durability: 100, power: 81, combat: 85 },
  },
  {
    id: 9,
    name: 'Aquaman',
    description: 'Arthur Curry',
    image: `${BASE}/md/9-aquaman.jpg`,
    images: {
      xs: `${BASE}/xs/9-aquaman.jpg`,
      sm: `${BASE}/sm/9-aquaman.jpg`,
      md: `${BASE}/md/9-aquaman.jpg`,
      lg: `${BASE}/lg/9-aquaman.jpg`,
    },
    publisher: 'DC Comics',
    alignment: 'good',
    firstAppearance: 'More Fun Comics #73',
    powerstats: { intelligence: 81, strength: 85, speed: 79, durability: 80, power: 83, combat: 80 },
  },
];

export const MOCK_SINGLE_HERO = MOCK_HEROES[0]; // Batman

export function createMockHero(overrides: Partial<Hero> = {}): Hero {
  return {
    id: 999,
    name: 'Test Hero',
    description: 'A test hero description for testing purposes',
    image: 'https://example.com/hero.jpg',
    images: {
      xs: 'https://example.com/hero.xs.jpg',
      sm: 'https://example.com/hero.sm.jpg',
      md: 'https://example.com/hero.md.jpg',
      lg: 'https://example.com/hero.lg.jpg',
    },
    publisher: 'Test Comics',
    alignment: 'good',
    firstAppearance: 'Test #1',
    ...overrides,
  };
}
