/**
 * Reads .env file and generates Angular environment files.
 * This runs before `ng build` so environment.ts has the real config.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const ENV_PATH = path.join(ROOT, '.env');

function loadEnv() {
  if (!fs.existsSync(ENV_PATH)) {
    console.warn('⚠ No .env file found. Using defaults.');
    return {};
  }

  const env = {};
  const lines = fs.readFileSync(ENV_PATH, 'utf-8').split('\n');

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;

    const key = trimmed.slice(0, eqIdx).trim();
    let value = trimmed.slice(eqIdx + 1).trim();

    // Remove surrounding quotes if present
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }

    env[key] = value;
  }

  return env;
}

function generateEnvironment(name, envVars, isProd) {
  // Read API_BASE_URL from .env or environment variables
  // In CI, this comes from GitHub Secrets via environment variables
  const apiBaseUrl = envVars.API_BASE_URL || process.env.API_BASE_URL || '';

  return `// Auto-generated by scripts/set-env.js — do not edit manually
export const environment = {
  production: ${isProd},
  environmentName: '${name}',
  apiBaseUrl: '${apiBaseUrl}',
};
`;
}

function main() {
  const env = loadEnv();

  const envDir = path.join(ROOT, 'src', 'environments');
  fs.mkdirSync(envDir, { recursive: true });

  // Default (used by `ng serve` without --configuration)
  fs.writeFileSync(path.join(envDir, 'environment.ts'), generateEnvironment('development', env, false));
  // Development config
  fs.writeFileSync(path.join(envDir, 'environment.development.ts'), generateEnvironment('development', env, false));
  // Staging config
  fs.writeFileSync(path.join(envDir, 'environment.staging.ts'), generateEnvironment('staging', env, true));
  // Production config
  fs.writeFileSync(path.join(envDir, 'environment.prod.ts'), generateEnvironment('production', env, true));

  console.log('✅ Environment files generated (no API key needed)');
}

main();
